name: Docs Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress --require-https --exclude-file .lycheeignore
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
