name: Docs Organization Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  check-root-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify root markdown placement
        run: |
          set -euo pipefail
ALLOWED=(README.md hayekian-site.md claude2.md SECURITY.md)
          mapfile -t ROOT_MDS < <(find . -maxdepth 1 -type f -name '*.md' -printf '%f\n' | sort)
          OFFENDERS=()
          for f in "${ROOT_MDS[@]}"; do
            ALLOWED_FLAG=0
            for a in "${ALLOWED[@]}"; do
              if [[ "$f" == "$a" ]]; then ALLOWED_FLAG=1; break; fi
            done
            if [[ $ALLOWED_FLAG -eq 0 ]]; then OFFENDERS+=("$f"); fi
          done
          if (( ${#OFFENDERS[@]} > 0 )); then
            echo "Root markdown offenders detected:" >&2
            printf ' - %s\n' "${OFFENDERS[@]}" >&2
            exit 1
          fi
          echo "Docs organization check passed."
